version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/Dockerfile
    container_name: frontend
    image: frontend
    restart: on-failure
    working_dir: /app
    ports:
      - '4173:4173'
    networks:
      - main
networks:
  main:
    driver: bridge
