version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: images/php/Dockerfile
    container_name: admin
    restart: on-failure
    image: admin
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DATABASE_CONTAINER}
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: ${DATABASE_DB}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./images/php/php.ini:/usr/local/etc/php/php.ini
      - ./admin:/home/app
      - /home/app/vendor
      - ./supervisors/admin:/etc/supervisor/conf.d/
    networks:
      - main
  npm:
    image: docker.arvancloud.ir/node:14
    volumes:
      - ./admin:/app
    working_dir: /app
    depends_on:
      - admin
    networks:
      - main
  backend:
    build:
      context: .
      dockerfile: images/backend/Dockerfile
    container_name: backend
    restart: on-failure
    image: backend
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - ./storage:/app/uploads
      - /app/node_modules
    command: npm run dev
    environment:
      DB_HOST: ${DATABASE_CONTAINER}
      DB_DATABASE: ${DATABASE_DB}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_PORT: ${DATABASE_PORT}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    deploy:
      replicas: 1
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.hostname == slave1 ]
    networks:
      - main
  frontend:
    build:
      context: .
      dockerfile: images/frontend/Dockerfile
    container_name: frontend
    image: frontend
    restart: on-failure
    working_dir: /app
    ports:
      - '4173:4173'
    networks:
      - main
  mysql:
    image: mysql
    container_name: ${DATABASE_CONTAINER}
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./shared/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - main
  phpmyadmin:
    image: docker.arvancloud.ir/phpmyadmin
    container_name: meet_phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 5050:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - main
  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3.8-management-alpine
    tty: true
    hostname: ${RABBITMQ_HOST}
    container_name: ${RABBITMQ_HOST}
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./shared/rabbitmq/data:/var/lib/rabbitmq/
      - ./shared/rabbitmq/log:/var/log/rabbitmq
    ports:
      - '5671:5671'
      - "5672:5672"
      - '15671:15671'
      - '15672:15672'
    networks:
      - main
  freeswitch:
    container_name: freeswitch
    image: safarov/freeswitch
    ports:
      - "5060:5060/udp"
      - "5080:5080/udp"
      - "64000-64100:64000-64100/udp"
      - "5066:5066/tcp"
      - "9443:7443"
    networks:
      - freeswitch

    environment:
      SOUND_RATES: "32000:48000"
      SOUND_TYPES: "en-us-allison"
      EPMD: "false"
      DUMPCAP: "false"
    volumes:
      - './freeswitch/configs/freeswitch:/etc/freeswitch'
      - './freeswitch/configs/freeswitch-sounds:/usr/share/freeswitch/sounds'
networks:
  main:
    driver: bridge
    name: main
