version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend/Dockerfile
    container_name: backend
    restart: on-failure
    image: backend
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./src
        target: /app
      - /app/node_modules
    depends_on:
      - mysql
    command: npm run dev
    deploy:
      replicas: 1
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.hostname == slave1 ]
    networks:
      - main
networks:
  main:
    driver: bridge
    name: main
