version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    container_name: admin_nginx
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./admin:/home/app
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin
    networks:
      - main
  admin:
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    container_name: admin_main
    restart: on-failure
    image: admin
    ports:
      - "9000:9000"
    volumes:
      - ./admin:/home/app
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - main
  npm:
    image: node:14
    volumes:
      - ./admin:/app
    working_dir: /app
    networks:
      - main
networks:
  main:
    driver: bridge
    name: main
