export const state = {
    localStream: null,
    videoStream: null,
    sound: false,
    user: null,
    peerConnections: Object,
    socket: Object,
    hiddenVideo: true,
    showing: false,
    updating: false,
    remoteStreams: Array,
    displayStream: null,
    shareScreen: false,
    logo: null,
    videoInputs: [],
    audioInputs: [],
    speakers: [],
    selectedVideoDevice: null,
    selectedSpeakerDevice: null,
    selectedAudioDevice: null,
}