version: '3.8'
services:
  mysql:
    image: mysql
    container_name: ${DATABASE_CONTAINER}
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - main
networks:
  main:
    driver: bridge
    name: main
